# Generated by Django 2.2.5 on 2019-09-19 14:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contenu',
            field=tinymce.models.HTMLField(default='null', verbose_name='Contenu'),
        ),
    ]
