# Generated by Django 2.2.5 on 2019-09-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_contenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
