# Generated by Django 2.2.5 on 2019-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
